modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
showAsResourcePack=false

[[mixins]]
config = "redstonejammer.mixins.json"

[[mods]]
modId="redstonejammer"
version="1.0.0"
displayName="Redstone Jammer"
authors="Mantoku"
description='''
Redstone Jammer introduces wireless redstone suppression, signal inversion, and automated pulse jamming countermeasures to Minecraft. Created by Mantoku.
'''

[[dependencies.redstonejammer]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.redstonejammer]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"
